site_name: Small Group Notes
site_url: http://smallgroupnotes.github.io
site_description: Small Group Notes
repo_url: https://github.com/smallgroupnotes/smallgroupnotes.github.io

remote_branch: master

theme: yeti # no search...
# theme: readthedocs # quotes look odd...

pages:
  - Home: index.md
  - Random Emails:
    - Cancelled: random/2012-09-10-cancelled.md
    - Evangelism: random/2013-01-30-evangelism.md
    - Predestination: random/2013-02-04-predestination.md
    - Remember who you are: random/2013-02-27-remember.md
    - Another Challenge: random/2013-03-07-another-challenge.md
    - Sermon on prayer: random/2013-10-14-sermon-on-prayer.md
    - Something more on prayer: random/2013-12-11-something-more.md
    - 2014 Recap: random/2014-12-31-2014-recap.md
  - Prayer 2013:
    - Prayer #1: prayer2013/prayer1.md
    - Prayer #2: prayer2013/prayer2.md
    - Prayer #3: prayer2013/prayer3.md
    - Prayer #3 Q&A: prayer2013/prayer3qa.md
    - Prayer #4: prayer2013/prayer4.md
    - Prayer #5: prayer2013/prayer5.md
    - Prayer #6: prayer2013/prayer6.md
