site_name: Small Group Notes
site_url: http://smallgroupnotes.github.io
site_description: Small Group Notes
repo_url: https://github.com/smallgroupnotes/smallgroupnotes.github.io

extra_css:
  - custom.css

remote_branch: master

google_analytics: ['UA-72657229-1', 'smallgroupnotes.github.io']

#theme: yeti # no search...
theme: readthedocs # quotes look odd... - fixed in custom.css

pages:
  - Home: index.md
  - Random Emails:
    - Cancelled: random/2012-09-10-cancelled.md
    - Evangelism: random/2013-01-30-evangelism.md
    - Predestination: random/2013-02-04-predestination.md
    - Remember who you are: random/2013-02-27-remember.md
    - Another Challenge: random/2013-03-07-another-challenge.md
    - Sermon on prayer: random/2013-10-14-sermon-on-prayer.md
    - Something more on prayer: random/2013-12-11-something-more.md
    - 2014 Recap: random/2014-12-31-2014-recap.md
    - 2015 Recap: random/2015-12-31-2015-recap.md 
  - Prayer 2013:
    - Prayer 1 - God Needs Prayer: prayer2013/prayer1.md
    - Prayer 2: prayer2013/prayer2.md
    - Prayer 3: prayer2013/prayer3.md
    - Prayer 3 Q&A: prayer2013/prayer3qa.md
    - Prayer 4: prayer2013/prayer4.md
    - Prayer 5 - Living in Communication: prayer2013/prayer5.md
    - Prayer 6: prayer2013/prayer6.md
  - Love 2014:
    - Love 1 - Knowing your name: love2014/love1.md
    - Love 2 - It's all about love part 1: love2014/love2.md
    - Love 2.5 - Intro to Love 3: love2014/love2_5.md
    - Love 3 - It's all about love part 2: love2014/love3.md
    - Love 3.5 - Knocking over the bear: love2014/love3_5.md
    - Love 4 - The only thing that matters: love2014/love4.md
    - Love 5: love2014/love5.md
    - Love 6: love2014/love6.md
    - Love 7: love2014/love7.md
    - Love 8: love2014/love8.md
    - Love 9 - Let Love Lead: love2014/love9.md
  - Beatitudes 2016:
    - Beatitudes 1 - Salt and Light: beatitudes2016/01-salt-and-light.md
